FROM node:20 as builder

WORKDIR /app
COPY lerobot-web-fe/package*.json ./
RUN npm ci
COPY lerobot-web-fe/ .
RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY docker/default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
